---
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:  

    - name: "deploy gradle on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      before_install:
        - java -version
      script:
        - sudo bash gradlew assemble
        - ./gradlew check
        - ./gradlew build #Build with Gradle
      after_success:
        - deactivate

    - name: "deploy blackduckcopilot gradle on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      before_install:
        - java -version
      script:
        - ./gradlew check
      after_success:
        # Upload to CoPilot
        - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
        - deactivate

    - name: "deploy codecov gradle on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      before_install:
        - java -version
      script:
        - ./gradlew check
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate

  # The command "~/bin/install-jdk.sh --target "/home/travis/openjdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "GPL" --cacerts" failed and exited with 3 during .
    # - name: "deploy codecov cobertura junit4 maven on focal amd64"
    #   dist: focal
    #   arch: amd64   
    #   language: java
    #   jdk:
    #   - openjdk8
    #   before_install:
    #     - java -version
    #   script:
    #     - mvn clean package
    #     - mvn cobertura:cobertura
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
        # - deactivate

  # Caused by: java.lang.ClassNotFoundException: org.apache.maven.doxia.siterenderer.DocumentContent
    # - name: "deploy maven checkstyle on bionic arm64"
    #   dist: bionic
    #   arch: amd64         
    #   language: java
    #   jdk:
    #   - openjdk8
    #   cache:
    #     directories:
    #     - ~/.m2
    #   before_install:
    #     - java -version
    #   script:
    #     - cd maven-checkstyle
    #     - mvn site
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    #     - deactivate

# JDKs installed for Bionic
# https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support
    # - name: "deploy checkstyle codecov maven(single pom)  on bionic arm64"
    #   dist: bionic
    #   arch: amd64         
    #   language: java
    #   jdk:
    #   - openjdk8
    #   - openjdk10
    #   - openjdk11 #default 
    #   cache:
    #     directories:
    #     - ~/.m2
    #   before_install:
    #     - java -version
    #   script:
    #     - cd maven-checkstyle
    #     - mvn checkstyle:checkstyle
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    #     - deactivate

# JDKs installed for Bionic
# https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support
    # - name: "deploy checkstyle codecov maven(single pom)  on xenial arm64"
    #   dist: xenial
    #   arch: amd64         
    #   language: java
    #   jdk:
    #   - openjdk8
    #   - openjdk10
    #   - openjdk11 #default 
    #   cache:
    #     directories:
    #     - ~/.m2
    #   before_install:
    #     - java -version
    #   script:
    #     - cd maven-checkstyle
    #     - mvn checkstyle:checkstyle
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    #     - deactivate

    # The requested profile "github-maven-repo" could not be activated because it does not exist.
    # - name: "deploy maven checkstyle on bionic arm64"
    #   dist: bionic
    #   arch: amd64         
    #   language: java
    #   addons:
    #     apt:
    #       packages:
    #         - xmlstarlet
    #   jdk:
    #   - openjdk8
    #   cache:
    #     directories:
    #     - ~/.m2
    #   before_install:
    #     - java -version
    #   script:
    #     - MVN_SETTINGS=${TRAVIS_HOME}/.m2/settings.xml
    #     - xmlstarlet ed --inplace -d "//mirrors" $MVN_SETTINGS
    #     - cd maven-checkstyle
    #     - mvn checkstyle:checkstyle -Pgithub-maven-repo
    #     - mvn -f pom-google-custom-suppression.xml clean checkstyle:checkstyle -Pgithub-maven-repo
    #     - grep "error" target/checkstyle-result.xml
    #     - mvn -f pom-google.xml clean checkstyle:checkstyle -Pgithub-maven-repo
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    #     - deactivate

    # - name: "deploy codecov cobertura junit4 maven(single pom) on bionic arm64"
    #   dist: bionic
    #   arch: amd64         
    #   language: java
    #   jdk:
    #   - openjdk8
    #   before_install:
    #     - java -version
    #   script:
    #     - cd codecov-test2
    #     - mvn clean package
    #     - mvn cobertura:cobertura
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    #     - deactivate

    # - name: "deploy codecov cobertura junit4 maven(parent-child pom) on bionic arm64"
    #   dist: bionic
    #   arch: amd64         
    #   language: java
    #   jdk:
    #   - openjdk8
    #   before_install:
    #     - java -version
    #   script:
    #     - mvn clean package
    #     - mvn cobertura:cobertura
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    #     - deactivate
