---
# sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:  

    # - name: "build lua on macOS 10.15.7 osx xcode12.2"
    #   sudo: required
    #   os: osx
    #   # arch: i386 
    #   osx_image:
    #     - xcode12.2 #macOS 10.15.7
    #   addons:
    #     homebrew:
    #       packages:
    #       - node
    #       - python
    #       - git
    #       - tar
    #       update: true
    #   language: c
    #   env:
    #     global:
    #       - LUAROCKS=2.2.2
    #     matrix:
    #     - LUA=lua5.1
    #     - LUA=lua5.2
    #     - LUA=lua5.3
    #   before_install:
    #     - source app/setenv_lua.sh 
    #     - luarocks install luacov
    #     - luarocks install tapered  
    #   script:
    #     - lua -lluacov app/awesome-tests.lua      
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    #     - deactivate

    # - name: "build lua on macOS 10.15.7 osx xcode12.2"
    #   sudo: required
    #   os: osx
    #   # arch: i386 
    #   osx_image:
    #     - xcode12.2 #macOS 10.15.7
    #   addons:
    #     homebrew:
    #       packages:
    #       - node
    #       - python
    #       - git
    #       - tar
    #       update: true
    #   language: c
    #   # env:
    #   #   global:
    #   #     - LUAROCKS=2.2.2
    #   #   matrix:
    #   #   - LUA=lua5.1
    #   #   - LUA=lua5.2
    #   #   - LUA=lua5.3
    #   before_install:
    #     - sudo make deploy-lua-app 
    #     - luarocks install luacov
    #     - luarocks install tapered  
    #   script:
    #     - lua -lluacov app/awesome-tests.lua      
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)
    #     - deactivate

    # - name: "build lua w codecov on bionic arm64"
    #   osx: linux
    #   dist: bionic
    #   sudo: false
    #   install: true
    #   arch: amd64  
    #   language: c
    #   # env:
    #   #   global:
    #   #   - LUAROCKS=2.2.2
    #   #   matrix:
    #   #   - LUA=lua5.1
    #   #   - LUA=lua5.2
    #   #   - LUA=lua5.3
    #   before_install:
    #     - make deploy-lua-app 
    #     - luarocks install luacov
    #     - luarocks install tapered  
    #   script:
    #     - lua -lluacov app/awesome-tests.lua    
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)        
    #     - deactivate
    
    # - name: "build lua w codecov on bionic arm64"
    #   osx: linux
    #   dist: bionic
    #   sudo: false
    #   install: true
    #   arch: amd64  
    #   language: c
    #   env:
    #     global:
    #     - LUAROCKS=2.2.2
    #     matrix:
    #     - LUA=lua5.1
    #     - LUA=lua5.2
    #     - LUA=lua5.3
    #   before_install:
    #     - source app/setenv_lua.sh 
    #     - luarocks install luacov
    #     - luarocks install tapered  
    #   script:
    #     - lua -lluacov app/awesome-tests.lua    
    #   after_success:
    #     - bash <(curl -s https://codecov.io/bash)        
    #     - deactivate

    - name: "build lua w codecov on bionic arm64"
      osx: linux
      dist: bionic
      sudo: required
      arch: amd64  
      language: erlang
      env:
        - LUA=""
        - LUA="luajit"
      install:
      - sudo apt-get install -qqy luajit 
      - sudo apt-get install -qqy luarocks #luarocks is the "ruby gems" of Lua
      - sudo luarocks install -qqy luafilesystem
      - sudo luarocks install -qqy busted
      script:
        - "busted spec"  
      after_success:
        - bash <(curl -s https://codecov.io/bash)        
        - deactivate

    - name: "build lua on macOS 10.15.7 osx xcode12.2"
      sudo: required
      os: osx
      # arch: i386 
      osx_image:
        - xcode12.2 #macOS 10.15.7
      language: erlang
      env:
      - LUA=""
      - LUA="luajit"
      addons:
        homebrew:
          packages:
          - luajit
          - luarocks  #luarocks is the "ruby gems" of Lua
          update: true
      script:
        - "busted spec"    
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate        