name: "checkstyle pmd findbugs blackduckcopilot Gradle CI"

on:
  push:
    branches: [ githubactions ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  



jobs:
  # build:

  gradle-checkstyle-pmd-findbugs-blackduckcopilot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "build gradle w checkstyle pmd findbugs blackduckcopilot  on bionic arm64"      
      run: |
            pwd
            ls -lai
            cd app6 && chmod +x gradlew
            pwd
            ls -lai
            # ./gradlew clean check
            # ./gradlew clean build
            # bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)          
    # - name: Change dir
    #   run: cd app6 && chmod +x gradlew
    # - name: Run Checks
    #   run: cd app6 &&  "./gradlew clean check"    
    # - name: Buil Application
    #   run: cd app6 && "./gradlew clean build"       
    # - name: Upload to CoPilot
    #   run: "bash <(curl -s https://copilot.blackducksoftw1are.com/ci/travis/scripts/upload)" 
