name: GradleCI

# on:
#   push:
#     branches: [ githubactions ]
#   pull_request:
#     branches: [ githubactions ]
on: [push, pull_request]

jobs:
  # build:

  gradle-checkstyle-pmd-findbugs-blackduckcopilot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Change dir
      run: cd app6 && chmod +x gradlew
    - name: Run Checks
      run: cd app6 &&  "./gradlew clean check"    
    - name: Buil Application
      run: cd app6 && "./gradlew clean build"       
    - name: Upload to CoPilot
      run: "bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)" 

  gradle-make-findbugs-blackduckcopilot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: sudo make deploy-app4

  gradle-make-jacoco-coveralls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: sudo make deploy-app5
      
  gradle-jacoco-coveralls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Change dir
      run: cd app5 && chmod +x gradlew
    - name: Build with Gradle
      run: "./gradlew clean build"    
    - name: Create jacoco coveralls report
      run: "./gradlew jacocoTestReport coveralls"             

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!