name: GradleCI

on:
  push:
    branches: [ githubactions ]
  pull_request:
    branches: [ githubactions ]
# on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: os fingerprinting
      run: hostnamectl status    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build